### ISSUE TITLE
FormulaR1C1 parser messing with formula

### ISSUE THREAD

**Issue by Szer** [pruiz/EPPlus#4]
Test case:
//_ws is some worksheet.
var deptColumn = 59;
var startRow = 5;
var k = 5;
var i = 70;

var formulaStr = $@"=SUMIF(R5C{deptColumn}:R{i + startRow}C{deptColumn};""="" & RC{deptColumn};R5C{k}:R{i + startRow}C{k})";

What I Expect:
Cell formula should be:
SUMIF(R5C59:R75C59;"=" & RC59;R5C5:R75C5)";

What I get in case _ws.Cells[i,k].FormulaR1C1 = formulaStr;
SUMIF(R5C59:"="R81C59; & RC59;R5C6:R81C6)"

What I get in case _ws.Cells[i,k].Formula = formulaStr;
"=SUMIF(R5C59:R81C59;"=" & RC59;R5C6:R81C6)"

Somehow "=" moved left if I use FormulaR1C1 parser

**Comment by pruiz** [comment]
Sorry, this is not the main site for EPPlus. Just my own repo.

Try posting your issue at: http://epplus.codeplex.com/
