### ISSUE TITLE
"_" replaced by " " from Header column

### ISSUE THREAD

**Issue by RavindraBarapatre** [pruiz/EPPlus#6]
Hello,

We are using EPPlus for export excel, while we are doing this. We observed one issue.

we have column with underscore. when it create ExcelWorksheet it replace _ with space.
e.g.

public class table{
   public guid RulesEngineRule_Id;
}
when we export it, we see **_** is replace by **space**.

![underscoreissue](https://cloud.githubusercontent.com/assets/11921979/21923403/e6fb7c40-d999-11e6-94e1-c546e0f86d36.PNG)

Please check.

**Comment by pruiz** [comment]
Sorry, this is not the main site for EPPlus. Just my own repo.

Try posting your issue at: http://epplus.codeplex.com/
